export const orderInfo = {
  id: "ORD001",
  createdAt: "2025-01-05T09:15:00Z",
  status: "processing",
  addrees: "32 Adebisi Oyenola Street",

  product: {
    id: "PRD001",
    productName: "Raw Cashew Nuts",
    createdAt: "2025-01-05T10:22:00Z",
    status: "processing",
    price: "$250",
    country: "Nigeria",
    minOrder: "10 tons",
    quantity: "50 tons",

    minLead: 7,
    minLeadPeriod: "days",
    maxLead: 14,
    maxLeadPeriod: "days",
    description:
      "High-quality raw cashew nuts sourced directly from Nigerian farmers. Well-dried, clean, and export-ready.",
    productImages: [
      { id: "IMG01", imgUrl: "/assets/dummy/prodImg.jpg" },
      { id: "IMG02", imgUrl: "/assets/dummy/prodImg1.jpg" },
      { id: "IMG03", imgUrl: "/assets/dummy/prodImg2.jpg" },
      { id: "IMG04", imgUrl: "/assets/dummy/prodImg3.jpg" },
      { id: "IMG05", imgUrl: "/assets/dummy/prodImg4.jpg" },
    ],
    category: "Nuts & Seeds",
    rating: 4.5,
    reviews: 20,
  },

  seller: {
    id: "SELL001",
    firstName: "Adewale ",
    lastName: "Farms",
    email: "contact@adewalefarms.com",
    phoneNumber: "+2348012345678",
    country: "Nigeria",
    companyName: "Adewale Agro Exporters Ltd",
  },

  buyer: {
    id: "BUY001",
    firstName: "Global",
    lastName: "Foods Import LLC",
    email: "info@globalfoods.com",
    phoneNumber: "+1 202 555 0192",
    country: "USA",
    companyName: "Global Foods Import LLC",
  },
};

export const orders = [
  {
    id: "ORD001",
    createdAt: "2025-01-05T09:15:00Z",
    productName: "Raw Cashew Nuts",
    productId: "PRD001",
    quantity: 10,
    unit: "tons",
    price: "$250",
    amount: "$2,500",
    status: "pending",
    minLead: 7,
    maxLead: 14,
    minLeadPeriod: "days",
    maxLeadPeriod: "days",
  },
  {
    id: "ORD002",
    createdAt: "2025-01-06T11:30:00Z",
    productName: "Sesame Seeds",
    productId: "PRD002",
    quantity: 5,
    unit: "tons",
    price: "₦270,000",
    amount: "₦1,350,000",
    status: "processing",
    minLead: 1,
    maxLead: 2,
    minLeadPeriod: "weeks",
    maxLeadPeriod: "weeks",
  },
  {
    id: "ORD003",
    createdAt: "2025-01-07T14:22:00Z",
    productName: "Soya Beans",
    productId: "PRD003",
    quantity: 800,
    unit: "kg",
    price: "$120",
    amount: "$960",
    status: "in_transit",
    minLead: 4,
    maxLead: 9,
    minLeadPeriod: "days",
    maxLeadPeriod: "days",
  },
  {
    id: "ORD004",
    createdAt: "2025-01-08T08:50:00Z",
    productName: "Ginger (Dried Split)",
    productId: "PRD004",
    quantity: 300,
    unit: "bags",
    price: "₦420,000",
    amount: "₦1,260,000",
    status: "delivered",
    minLead: 2,
    maxLead: 4,
    minLeadPeriod: "weeks",
    maxLeadPeriod: "weeks",
  },
  {
    id: "ORD005",
    createdAt: "2025-01-09T10:00:00Z",
    productName: "Maize",
    productId: "PRD005",
    quantity: 20,
    unit: "tons",
    price: "$90",
    amount: "$1,800",
    status: "declined",
    minLead: 7,
    maxLead: 30,
    minLeadPeriod: "days",
    maxLeadPeriod: "days",
  },
  {
    id: "ORD006",
    createdAt: "2025-01-10T12:45:00Z",
    productName: "Cocoa Beans",
    productId: "PRD006",
    quantity: 2,
    unit: "tons",
    price: "$450",
    amount: "$900",
    status: "pending",
    minLead: 1,
    maxLead: 1,
    minLeadPeriod: "months",
    maxLeadPeriod: "months",
  },
  {
    id: "ORD007",
    createdAt: "2025-01-11T09:30:00Z",
    productName: "Palm Kernel",
    productId: "PRD007",
    quantity: 700,
    unit: "kg",
    price: "₦300,000",
    amount: "₦2,100,000",
    status: "received",
    minLead: 5,
    maxLead: 9,
    minLeadPeriod: "days",
    maxLeadPeriod: "days",
  },
  {
    id: "ORD008",
    createdAt: "2025-01-12T16:12:00Z",
    productName: "Shea Nuts",
    productId: "PRD008",
    quantity: 4,
    unit: "tons",
    price: "$150",
    amount: "$600",
    status: "processing",
    minLead: 2,
    maxLead: 3,
    minLeadPeriod: "weeks",
    maxLeadPeriod: "weeks",
  },
  {
    id: "ORD009",
    createdAt: "2025-01-13T07:22:00Z",
    productName: "Tiger Nuts",
    productId: "PRD009",
    quantity: 120,
    unit: "bags",
    price: "₦165,000",
    amount: "₦165,000",
    status: "in_transit",
    minLead: 7,
    maxLead: 14,
    minLeadPeriod: "days",
    maxLeadPeriod: "days",
  },
  {
    id: "ORD010",
    createdAt: "2025-01-14T14:40:00Z",
    productName: "White Rice (Milled)",
    productId: "PRD010",
    quantity: 15,
    unit: "tons",
    price: "$350",
    amount: "$5,250",
    status: "delivered",
    minLead: 3,
    maxLead: 6,
    minLeadPeriod: "weeks",
    maxLeadPeriod: "weeks",
  },
];
