import { Payment } from "../types";

export const payments: Payment[] = [
  {
    orderId: "ORD-001",
    productName: "Raw Cashew Nuts",
    productId: "PRD-001",
    paymentType: "debit",
    status: "completed",
    transactionType: "transfer",
    amount: "$250",
    createdAt: "2025-01-10T09:22:00Z",
  },
  {
    orderId: "ORD-002",
    productName: "Sesame Seeds",
    productId: "PRD-002",
    paymentType: "credit",
    status: "pending",
    transactionType: "card",
    amount: "₦450000",
    createdAt: "2025-01-11T14:10:00Z",
  },
  {
    orderId: "ORD-003",
    productName: "Ginger",
    productId: "PRD-003",
    paymentType: "debit",
    status: "completed",
    transactionType: "transfer",
    amount: "$180",
    createdAt: "2025-01-12T08:55:00Z",
  },
  {
    orderId: "ORD-004",
    productName: "Cocoa Beans",
    productId: "PRD-004",
    paymentType: "credit",
    status: "declined",
    transactionType: "card",
    amount: "$320",
    createdAt: "2025-01-09T17:30:00Z",
  },
  {
    orderId: "ORD-005",
    productName: "Maize",
    productId: "PRD-005",
    paymentType: "debit",
    status: "completed",
    transactionType: "transfer",
    amount: "₦220000",
    createdAt: "2025-01-15T10:12:00Z",
  },
  {
    orderId: "ORD-006",
    productName: "Soybeans",
    productId: "PRD-006",
    paymentType: "credit",
    status: "pending",
    transactionType: "card",
    amount: "$150",
    createdAt: "2025-01-14T13:44:00Z",
  },
  {
    orderId: "ORD-007",
    productName: "Palm Kernel Oil",
    productId: "PRD-007",
    paymentType: "debit",
    status: "completed",
    transactionType: "transfer",
    amount: "$95",
    createdAt: "2025-01-13T16:30:00Z",
  },
  {
    orderId: "ORD-008",
    productName: "Paddy Rice",
    productId: "PRD-008",
    paymentType: "debit",
    status: "pending",
    transactionType: "transfer",
    amount: "₦350000",
    createdAt: "2025-01-12T11:55:00Z",
  },
  {
    orderId: "ORD-009",
    productName: "Shea Butter",
    productId: "PRD-009",
    paymentType: "credit",
    status: "completed",
    transactionType: "card",
    amount: "$70",
    createdAt: "2025-01-11T09:15:00Z",
  },
  {
    orderId: "ORD-010",
    productName: "Dried Hibiscus Flower",
    productId: "PRD-010",
    paymentType: "debit",
    status: "declined",
    transactionType: "transfer",
    amount: "$260",
    createdAt: "2025-01-13T07:42:00Z",
  },
];
